# Generated by Django 2.2.3 on 2020-01-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_id', models.IntegerField()),
                ('amount_paid', models.FloatField()),
                ('amount_debt', models.FloatField()),
                ('date_paid', models.DateTimeField()),
            ],
        ),
    ]
