# Generated by Django 2.2.3 on 2020-01-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255)),
                ('last_names', models.CharField(max_length=255)),
                ('card_id', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('region_id', models.IntegerField()),
                ('provincia_id', models.IntegerField()),
                ('comuna_id', models.IntegerField()),
                ('phone', models.CharField(max_length=50)),
                ('date_create', models.DateField()),
                ('date_update', models.DateField()),
            ],
        ),
    ]
